In [12]:
import numpy as np
from sklearn.datasets import fetch_openml as datasets
mnist_data = datasets("mnist_784")
x = mnist_data["data"]
y = mnist_data["target"]
x /= 255.0
num_labels = 10
examples = y.shape[0]
# y_new = one_hot(y.astype('int32'), num_labels)


In [3]:
print(y)

0        5
1        0
2        4
3        1
4        9
        ..
69995    2
69996    3
69997    4
69998    5
69999    6
Name: class, Length: 70000, dtype: category
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']


In [4]:
print(examples)

70000


In [7]:
print(y.astype('int32'))

0        5
1        0
2        4
3        1
4        9
        ..
69995    2
69996    3
69997    4
69998    5
69999    6
Name: class, Length: 70000, dtype: int32


In [8]:
y[:]

0        5
1        0
2        4
3        1
4        9
        ..
69995    2
69996    3
69997    4
69998    5
69999    6
Name: class, Length: 70000, dtype: category
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']

In [17]:
print(y[:,None]== np.arange(10))

ValueError: Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported. Convert to a numpy array before indexing instead.

In [19]:
# print(y[:,None]== np.arange(10))
print(np.arange(10), type(np.arange(10)))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [21]:
y

0        5
1        0
2        4
3        1
4        9
        ..
69995    2
69996    3
69997    4
69998    5
69999    6
Name: class, Length: 70000, dtype: category
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']

In [24]:
type(y)

pandas.core.series.Series

In [25]:
type(np.asarray(y))

numpy.ndarray

In [26]:
print(np.asarray(y)[:,None]== np.arange(10))

[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]


In [28]:
def one_hot(x, k, dtype=np.float32):
    return np.array(np.asarray(x)[:, None] == np.arange(k), dtype)

In [32]:
y_new = one_hot(y.astype('int32'), num_labels)

In [33]:
y_new


array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(70000, 10), dtype=float32)

In [34]:
train_size = 60000
test_size = x.shape[0] - train_size
x_train, x_test = x[:train_size], x[train_size:]

In [50]:
print(x_train, type(x_train))

       pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
59995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
59996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
59997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
59998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
59999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel7

In [44]:
x_test

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
60000     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
60001     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
60002     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
60003     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
60004     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
69995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
60000      0.0  ...       0.0       0.0       0.0       0.0       0.0   
60001      0.0  ...       0.0       0.0       0.0       0.0       0.0   
60002      0.0  ...       0.0       0.0       0.0       0.0       0.0   
60003      0.0  ...       0.0       0.0       0.0       0.0       0.0   
60004      0.0  ...       0.0       0.0       0.0       0.0       0.0   
...        ...  ...       ...       ...       ...       ...       ...   
69995      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69996      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69997      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69998      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69999      0.0  ...       0.0       0.0       0.0       0.0       0.0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
60000       0.0       0.0       0.0       0.0       0.0  
60001       0.0       0.0       0.0       0.0       0.0  
60002       0.0       0.0       0.0       0.0       0.0  
60003       0.0       0.0       0.0       0.0       0.0  
60004       0.0       0.0       0.0       0.0       0.0  
...         ...       ...       ...       ...       ...  
69995       0.0       0.0       0.0       0.0       0.0  
69996       0.0       0.0       0.0       0.0       0.0  
69997       0.0       0.0       0.0       0.0       0.0  
69998       0.0       0.0       0.0       0.0       0.0  
69999       0.0       0.0       0.0       0.0       0.0  

[10000 rows x 784 columns]

In [39]:
y_train, y_test = y_new[:train_size], y_new[train_size:]
shuffle_index = np.random.permutation(train_size)
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], shape=(60000, 10), dtype=float32)

In [40]:
shuffle_index

array([35158, 37731, 26499, ..., 12018, 21474,  6413], shape=(60000,))

In [73]:
x_train, y_train = x_train[shuffle_index], y_train[shuffle_index]

KeyError: "None of [Index([13607, 50396, 37426, 30428, 47452, 53929,  4715, 18199, 59997, 34626,\n       ...\n       52017, 54081, 42998,  1899,  2110, 40947, 25863, 40394, 48361, 59857],\n      dtype='int64', length=60000)] are in the [columns]"

In [48]:
x.shape

(70000, 784)

In [49]:
y.shape

(70000,)

In [54]:
perm = np.random.permutation(10)
print(perm)
import pandas as pd
fram = pd.DataFrame({'data': [1,2, 3, 4, 5, 6, 7, 8, 9, 10]})
print(fram)
print(fram[perm]) # KeyError: "None of [Index([7, 8, 4, 5, 9, 6, 3, 1, 0, 2], dtype='int64')] are in the [columns]"

[7 8 4 5 9 6 3 1 0 2]
   data
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10


KeyError: "None of [Index([7, 8, 4, 5, 9, 6, 3, 1, 0, 2], dtype='int64')] are in the [columns]"

In [57]:
fram['columns']

KeyError: 'columns'

In [58]:
fram

data
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10

In [60]:
type(x_train)

pandas.core.frame.DataFrame

In [68]:
npar = np.arange(100, 110)
npar

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [69]:
npar[perm]

array([107, 108, 104, 105, 109, 106, 103, 101, 100, 102])

In [70]:
perm

array([7, 8, 4, 5, 9, 6, 3, 1, 0, 2])

In [79]:
y_train

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(60000, 10), dtype=float32)

In [80]:
y_train.sum()

np.float32(60000.0)

In [81]:
type(y_train.sum())

numpy.float32

In [82]:
y_train.sum(keepdims=True)

array([[60000.]], dtype=float32)

In [84]:
type(y_train.sum(keepdims=True))

numpy.ndarray