In [1]:
import numpy as np

a = np.array(10)
atype = type(a)

print(a, atype, type(np.array(100)))

10 <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [3]:
a1d = [1, 2, 3, 4, 5]
a2d = [[1, 3, 5, 7], [2, 4, 6, 8]]
a3d = [[[1, 3], [1, 5]], [[2, 4], [2, 6]]]

print(a1d, type(a1d))
print(a2d, type(a2d))
print(a3d, type(a3d))

[1, 2, 3, 4, 5] <class 'list'>
[[1, 3, 5, 7], [2, 4, 6, 8]] <class 'list'>
[[[1, 3], [1, 5]], [[2, 4], [2, 6]]] <class 'list'>


In [12]:
a1d = np.array([1, 2, 3, 4, 5], dtype=np.int8)
a2d = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])
a3d = np.array([[[1, 3], [1, 5]], [[2, 4], [2, 6]]])

print(a1d, type(a1d))
print(a2d, type(a2d))
print(a3d, type(a3d))

[1 2 3 4 5] <class 'numpy.ndarray'>
[[1 3 5 7]
 [2 4 6 8]] <class 'numpy.ndarray'>
[[[1 3]
  [1 5]]

 [[2 4]
  [2 6]]] <class 'numpy.ndarray'>


In [15]:
a1d = np.array([300, 2, 3, 4, 5], dtype=np.int8)

OverflowError: Python integer 300 out of bounds for int8

In [18]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [19]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.eye(10, dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [24]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.random.permutation(10)

array([6, 2, 1, 4, 7, 9, 3, 5, 8, 0])